package net.justmili.trueend.init;

import net.justmili.trueend.block.*;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraft.world.level.block.Block;
import net.justmili.trueend.block.Wood;
import net.justmili.trueend.block.Wood6Sided;
import net.justmili.trueend.block.Leaves;
import net.justmili.trueend.block.WoodenPlanks;
import net.justmili.trueend.block.WoodenStairs;
import net.justmili.trueend.block.WoodenSlab;
import net.justmili.trueend.block.WoodenFence;
import net.justmili.trueend.block.WoodenFenceGate;
import net.justmili.trueend.block.WoodenDoor;
import net.justmili.trueend.block.WoodenTrapdoor;
import net.justmili.trueend.block.WoodenPressurePlate;
import net.justmili.trueend.block.WoodenButton;
import net.justmili.trueend.block.Stone;
import net.justmili.trueend.block.CoalOre;
import net.justmili.trueend.block.IronOre;
import net.justmili.trueend.block.GoldOre;
import net.justmili.trueend.block.RedstoneOre;
import net.justmili.trueend.block.DiamondOre;
import net.justmili.trueend.block.Sand;
import net.justmili.trueend.block.Obsidian;
import net.justmili.trueend.block.Gravel;
import net.justmili.trueend.block.GrassBlock;
import net.justmili.trueend.block.Glass;
import net.justmili.trueend.block.Dirt;
import net.justmili.trueend.block.Cobblestone;
import net.justmili.trueend.block.MossyCobblestone;
import net.justmili.trueend.block.Farmland;
import net.justmili.trueend.block.BeyondTheDreamPortal;
import net.justmili.trueend.TrueEnd;

public class TrueEndBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, TrueEnd.MODID);
	public static final RegistryObject<Block> DIRT = REGISTRY.register("dirt", () -> new Dirt());
	public static final RegistryObject<Block> GRASS_BLOCK = REGISTRY.register("grass_block", () -> new GrassBlock());
	public static final RegistryObject<Block> FARMLAND = REGISTRY.register("farmland", () -> new Farmland());
	public static final RegistryObject<Block> COBBLESTONE = REGISTRY.register("cobblestone", () -> new Cobblestone());
	public static final RegistryObject<Block> MOSSY_COBBLESTONE = REGISTRY.register("mossy_cobblestone", () -> new MossyCobblestone());
	public static final RegistryObject<Block> STONE = REGISTRY.register("stone", () -> new Stone());
	public static final RegistryObject<Block> COAL_ORE = REGISTRY.register("coal_ore", () -> new CoalOre());
	public static final RegistryObject<Block> IRON_ORE = REGISTRY.register("iron_ore", () -> new IronOre());
	public static final RegistryObject<Block> GOLD_ORE = REGISTRY.register("gold_ore", () -> new GoldOre());
	public static final RegistryObject<Block> REDSTONE_ORE = REGISTRY.register("redstone_ore", () -> new RedstoneOre());
	public static final RegistryObject<Block> DIAMOND_ORE = REGISTRY.register("diamond_ore", () -> new DiamondOre());
	public static final RegistryObject<Block> WOOD = REGISTRY.register("wood", () -> new Wood());
	public static final RegistryObject<Block> WOODEN_PLANKS = REGISTRY.register("wooden_planks", () -> new WoodenPlanks());
	public static final RegistryObject<Block> WOODEN_STAIRS = REGISTRY.register("wooden_stairs", () -> new WoodenStairs());
	public static final RegistryObject<Block> WOODEN_SLAB = REGISTRY.register("wooden_slab", () -> new WoodenSlab());
	public static final RegistryObject<Block> FENCE = REGISTRY.register("fence", () -> new WoodenFence());
	public static final RegistryObject<Block> FENCE_GATE = REGISTRY.register("fence_gate", () -> new WoodenFenceGate());
	public static final RegistryObject<Block> DOOR = REGISTRY.register("door", () -> new WoodenDoor());
	public static final RegistryObject<Block> TRAPDOOR = REGISTRY.register("trapdoor", () -> new WoodenTrapdoor());
	public static final RegistryObject<Block> PRESSURE_PLATE = REGISTRY.register("pressure_plate", () -> new WoodenPressurePlate());
	public static final RegistryObject<Block> BUTTON = REGISTRY.register("button", () -> new WoodenButton());
	public static final RegistryObject<Block> LEAVES = REGISTRY.register("leaves", () -> new Leaves());
	public static final RegistryObject<Block> OBSIDIAN = REGISTRY.register("obsidian", () -> new Obsidian());
	public static final RegistryObject<Block> GRAVEL = REGISTRY.register("gravel", () -> new Gravel());
	public static final RegistryObject<Block> WOOD_6_SIDED = REGISTRY.register("wood_6_sided", () -> new Wood6Sided());
	public static final RegistryObject<Block> BEYOND_THE_DREAM_PORTAL = REGISTRY.register("beyond_the_dream_portal", () -> new BeyondTheDreamPortal());
	public static final RegistryObject<Block> GLASS = REGISTRY.register("glass", () -> new Glass());
	public static final RegistryObject<Block> SAND = REGISTRY.register("sand", () -> new Sand());
}
